// ignore_for_file: avoid_print
import "package:flutter/material.dart";
import "package:provider/provider.dart";

import "package:share_plus/share_plus.dart";
import "package:url_launcher/url_launcher.dart";
import 'package:flutter_slidable/flutter_slidable.dart';

import "package:band_namer/band_name_factory.dart";
import "package:band_namer/user_data.dart";
import "package:band_namer/word_lists.dart";

const String __VERSION__ = "0.3.0";

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    print("Starting...");
    await WordLists.load();
    print("WordLists loaded.");

    await UserData.load();
    print("UserData loaded.");

    runApp(const BandNameGenerator());
  } catch (e, st) {
    print("ERROR: $e");
    print(st);
    rethrow;
  }
}

class BandNameGenerator extends StatelessWidget {
  const BandNameGenerator({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (context) => BandNameGeneratorState(),
      child: MaterialApp(
        title: "Namer App",
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal),
        ),
        home: HomePage(),
      ),
    );
  }
}

class BandNameGeneratorState extends ChangeNotifier {
  BandNameFactory factory = BandNameFactory();
  late String current = factory.construct();

  void getNext() {
    current = factory.construct();
    notifyListeners();
  }

  void toggleFavorite(String item) {
    if (UserData.favorites.contains(item)) {
      UserData.favorites.remove(item);
    } else {
      UserData.favorites.add(item);
    }
    UserData.save();
    notifyListeners();
  }

  void clearFavorites() {
    UserData.clear();
    notifyListeners();
  }
}

class HomePage extends StatefulWidget {
  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  var selectedIndex = 0;

  @override
  Widget build(BuildContext context) {
    Widget page;
    switch (selectedIndex) {
      case 0:
        page = GeneratorPage();
      case 1:
        page = FavoritesPage();
      case 2:
        page = InfoPage();
      default:
        throw UnimplementedError("no widget for $selectedIndex");
    }
    return Scaffold(
      body: Row(
        children: [
          SafeArea(
            child: NavigationRail(
              extended: false,
              destinations: [
                NavigationRailDestination(
                  icon: Icon(Icons.home),
                  label: Text("Home"),
                ),
                NavigationRailDestination(
                  icon: Icon(Icons.favorite),
                  label: Text("Favorites"),
                ),
                NavigationRailDestination(
                  icon: Icon(Icons.info),
                  label: Text("Info"),
                ),
              ],
              selectedIndex: selectedIndex,
              onDestinationSelected: (value) {
                setState(() {
                  selectedIndex = value;
                });
              },
            ),
          ),
          Expanded(
            child: Container(
              color: Theme.of(context).colorScheme.primaryContainer,
              child: page,
            ),
          ),
        ],
      ),
    );
  }
}

class GeneratorPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var appState = context.watch<BandNameGeneratorState>();
    var current = appState.current;

    IconData favoritesIcon;
    if (UserData.favorites.contains(current)) {
      favoritesIcon = Icons.favorite;
    } else {
      favoritesIcon = Icons.favorite_border;
    }

    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          BigCard(current: current),
          SizedBox(height: 10),
          Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              ElevatedButton.icon(
                onPressed: () {
                  appState.toggleFavorite(current);
                },
                icon: Icon(favoritesIcon),
                label: Text("Favorite"),
              ),
              SizedBox(width: 10),
              ElevatedButton.icon(
                onPressed: () {
                  SharePlus.instance.share(
                    ShareParams(
                      text:
                          "Dibs on the band name: $current\n\nGenerated by https://schwartstack.github.io/band_namer",
                    ),
                  );
                },
                icon: Icon(Icons.ios_share),
                label: Text("Share"),
              ),
              SizedBox(width: 10),
              ElevatedButton.icon(
                onPressed: () {
                  appState.getNext();
                },
                icon: Icon(Icons.navigate_next),
                label: Text("Next"),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class BigCard extends StatelessWidget {
  const BigCard({super.key, required this.current});

  final String current;

  @override
  Widget build(BuildContext context) {
    var theme = Theme.of(context);
    final style = theme.textTheme.displayMedium!.copyWith(
      color: theme.colorScheme.onPrimary,
    );

    return Card(
      color: theme.colorScheme.primary,
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Text(current, style: style),
      ),
    );
  }
}

class FavoritesPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var appState = context.watch<BandNameGeneratorState>();

    return ListView(
      children: [
        Padding(
          padding: const EdgeInsets.all(20),
          child: Text(
            "You have "
            "${UserData.favorites.length} favorite${UserData.favorites.length == 1 ? "" : "s"}:",
          ),
        ),
        for (var fav in UserData.favorites)
          Slidable(
            key: ValueKey(fav),
            startActionPane: ActionPane(
              motion: const StretchMotion(),
              children: [
                SlidableAction(
                  onPressed: (_) {
                    appState.toggleFavorite(fav);
                  },
                  icon: Icons.delete,
                  label: 'Delete',
                ),
              ],
            ),
            endActionPane: ActionPane(
              motion: const StretchMotion(),
              children: [
                SlidableAction(
                  onPressed: (_) {
                    SharePlus.instance.share(
                      ShareParams(
                        text:
                            "Dibs on the band name: $fav\n\nGenerated by https://schwartstack.github.io/band_namer",
                      ),
                    );
                  },
                  icon: Icons.share,
                  label: 'Share',
                ),
              ],
            ),
            child: ListTile(title: Text(fav)),
          ),
        SizedBox(height: 10),
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ElevatedButton.icon(
              onPressed: UserData.favorites.isNotEmpty
                  ? () {
                      appState.clearFavorites();
                    }
                  : null,
              icon: Icon(Icons.delete_forever),
              label: Text("Remove all favorites"),
            ),
            SizedBox(width: 10),
            ElevatedButton.icon(
              onPressed: UserData.favorites.isNotEmpty
                  ? () {
                      SharePlus.instance.share(
                        ShareParams(
                          text:
                              "My favorite new band name ideas:\n\n${UserData.favorites.join("\n")}\n\nGenerated by https://schwartstack.github.io/band_namer",
                        ),
                      );
                    }
                  : null,
              icon: Icon(Icons.ios_share),
              label: Text("Share"),
            ),
          ],
        ),
      ],
    );
  }
}

class InfoPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            "This is a Flutter app written in Dart by Jonathan Schwartz, a data scientist from San Jose, CA.",
          ),
          SizedBox(height: 100),
          ElevatedButton.icon(
            onPressed: () {
              launchUrl(Uri.parse("mailto:jzs1986@gmail.com"));
            },
            icon: Icon(Icons.email),
            label: Text("Email me"),
          ),
          SizedBox(height: 10),
          ElevatedButton.icon(
            onPressed: () {
              launchUrl(Uri.parse("https://github.com/schwartstack"));
            },
            icon: Icon(Icons.code),
            label: Text("Check out my github"),
          ),
          SizedBox(height: 10),
          ElevatedButton.icon(
            onPressed: () {
              launchUrl(Uri.parse("http://www.linkedin.com/in/schwartstack"));
            },
            icon: Icon(Icons.web),
            label: Text("Check out my LinkedIn"),
          ),
          SizedBox(height: 10),
          ElevatedButton.icon(
            onPressed: () {
              launchUrl(Uri.parse("https://ko-fi.com/schwartstack"));
            },
            icon: Icon(Icons.coffee),
            label: Text("Buy me a coffee"),
          ),
          Align(
            alignment: Alignment.bottomCenter,
            child: Padding(
              padding: const EdgeInsets.all(100.0),
              child: Text(
                "ver. $__VERSION__",
                style: TextStyle(fontSize: 14, color: Colors.grey),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
